sudo: required

services:
  - docker

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- rm -r -f $HOME/.ivy2/local/
language: scala
script:
- sbt formatAll
- if [[ -n $(git status -s) ]]; then git status && echo 'You need to format your code!'  && exit 1; fi
- sbt clean coverage compileAll test coverageReport || exit 1

jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
